console.log("正在载入云轩api V1.0...");
console.log("......");
console.log("载入成功");
console.log("----------------");
console.log("version：1.0.3");
console.log("version date：2020/03/17");
console.log("");
console.log("");
console.log("官方博客 http://www.xcen.xyz/");
console.log("官方社区 http://www.xcen.xyz/bbs");
console.log("");
console.log("还有，你打开了控制台是想干什么QAQ？！");